### ISSUE TITLE
ResClass未初始化，请确保你已经添加了必要的资源。同时确保你在混淆文件中添加了

### ISSUE THREAD

**Issue by pencilso** [umeng/MultiFunctionAndroidDemo#4]
直接上图
![qq 20180419183712](https://user-images.githubusercontent.com/16483654/38987043-038d8434-4401-11e8-961a-c1fc22c7270a.jpg)
这不知道是个什么鬼，照着文档上一步一步的来的。
然后我也尝试丢了个图标 改名为umeng_push_notification_default_large_icon  然后放到drawable目录中
却还是不行，然后我在后台 自定义图标  也还是不行....
日了狗了  气死了

**Comment by DarkSherlock** [comment]
Android Studio开发工具是基于gradle的配置方式，资源文件的包和应用程序的包是可以分开的，为了正确的找到资源包名，为开发者提供了自定义的设置资源包的接口。当资源包名和应用程序包名不一致时，调用设置资源包名的接口：
mPushAgent.setResourcePackageName(String packageName);
