### ISSUE TITLE
为什么你们的demo里面没有调用init方法

### ISSUE THREAD

**Issue by wwwchina** [umeng/MultiFunctionAndroidDemo#46]

**Comment by shineabel** [comment]
他这个demo根本就不工作的

**Comment by lydlovexyz** [comment]
调用了,老铁
<img width="795" alt="微信截图_20190821181239" src="https://user-images.githubusercontent.com/19246347/63423629-50420b00-c43f-11e9-9101-a2eebdcb49cb.png">

**Comment by wwwchina** [comment]
谢谢你的回答。
